# This file is automatically generated by Flutter.
# It defines the plugins that need to be included for this build.

set(FLUTTER_PLUGIN_LIST
  # Example: my_plugin
)

foreach(plugin ${FLUTTER_PLUGIN_LIST})
  add_subdirectory(${plugin})
endforeach()


